tap "homebrew/bundle"
brew "bat"
brew "exa"
brew "jq"
brew "procs"
brew "fd"
brew "fzf"
brew "gh"
brew "tree-sitter"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "wget"
brew "yadm"
brew "yarn"
brew "starship"
brew "awscli"
brew "asdf"
brew "tealdeer"

load "~/.config/brewfile/.Brewfile.#{/darwin/i =~ `uname -a` ? 'darwin' : 'linux'}"
