views:
  v1/pods:
    columns:
      - TYPETAG:.metadata.labels.type
      - NAME
      # - TAG:.metadata.labels.app
      - AGE
      - READY
      - RESTARTS
      # - CPU
      - "%CPU/R"
      - "%CPU/L"
      - MEM
      - "%MEM/R"
      - "%MEM/L"
      - STATUS
      - PF
      - IP
      - NODE
