[general]
import = [
    "~/.config/alacritty/themes/themes/nightfox.toml"
]

[font]
size = 15.0
normal = { family = "FiraMono Nerd Font", style = "Regular" }
bold = { family = "FiraMono Nerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[scrolling]
history = 100000

[window]
option_as_alt = "Both"
