theme = "mellow"

[editor]
line-number = "absolute"
cursorline = true
bufferline = "multiple"
color-modes = true
auto-format = false
# Custom Functions and Commands
# commands = { copy_git_path = "gbrowse.open_on_github" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"
mode.normal = "[N]"
mode.insert = "[I]"
mode.select = "[V]"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.lsp]
display-messages = true

# [keys.normal.space]
# og = "copy_git_path"