[env]
MISE_RUBY_DEFAULT_PACKAGES_FILE = '~/.config/mise/default-gems'
MISE_NODE_DEFAULT_PACKAGES_FILE = '~/.config/"mise/default-npm-packages'

[tools]
node = '22'
ruby = '2.7.6'
zig = '0.13.0'
pnpm = '9.9.0'

[settings]
# configure `mise install` to always keep the downloaded archive
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default

